const XMB_SETTINGS_KEY="personal-xmb-user-settings";
const defaults={sound:true,soundVolume:.075,clock:true,hints:true,animations:true,theme:"default"};
function getUserSettings(){try{return {...defaults,...(JSON.parse(localStorage.getItem(XMB_SETTINGS_KEY))||{})};}catch{return {...defaults};}}
function saveUserSettings(v){localStorage.setItem(XMB_SETTINGS_KEY,JSON.stringify(v));}
function applyUserSettings(){const s=getUserSettings();document.body.classList.toggle("hide-clock",!s.clock);document.body.classList.toggle("hide-hints",!s.hints);document.body.classList.toggle("reduced-xmb-motion",!s.animations);window.xmbAudio?.setEnabled?.(s.sound);window.xmbAudio?.setVolume?.(s.soundVolume);if(s.theme&&typeof applyTheme==="function")applyTheme(s.theme);}
let settingsBranch=null;
function closeSettingsPanel(){settingsBranch?.remove();settingsBranch=null;window.xmbAudio?.back?.();}
function openSettingsPanel(section="general"){
 if(settingsBranch)settingsBranch.remove();
 const b=document.createElement("aside");b.id="settings-overlay";b.className="xmb-settings-branch";b.innerHTML='<div class="xmb-settings-branch-inner"><div class="xmb-settings-branch-header"><div><div class="settings-kicker">SETTINGS</div><h2 id="settings-branch-title"></h2></div><button class="settings-close" type="button">ESC</button></div><div id="settings-branch-content"></div></div>';document.body.appendChild(b);settingsBranch=b;b.querySelector(".settings-close").onclick=closeSettingsPanel;renderSettingsSection(section);window.xmbAudio?.select?.();
}
function renderSettingsSection(section){
 const s=getUserSettings(),c=settingsBranch.querySelector("#settings-branch-content"),t=settingsBranch.querySelector("#settings-branch-title"),themes=window.themesData||{};
 const d={general:["General Settings",'<label class="xmb-setting-row">Show Clock <input id="setting-clock" type="checkbox" '+(s.clock?"checked":"")+'></label><label class="xmb-setting-row">Navigation Hints <input id="setting-hints" type="checkbox" '+(s.hints?"checked":"")+'></label><label class="xmb-setting-row">Animations <input id="setting-animations" type="checkbox" '+(s.animations?"checked":"")+'></label>'],audio:["Audio Settings",'<label class="xmb-setting-row">Sound Effects <input id="setting-sound" type="checkbox" '+(s.sound?"checked":"")+'></label><label class="xmb-setting-row">Volume <input id="setting-volume" type="range" min="0" max=".15" step=".005" value="'+s.soundVolume+'"></label>'],themes:["Themes",'<label class="xmb-setting-row">Theme <select id="setting-theme"></select></label>'],artwork:["Artwork",'<button id="setting-clear-cache" class="settings-action">Clear Artwork Cache</button><div id="settings-cache-status" class="settings-status"></div>'],system:["System",'<button id="setting-maximize" class="settings-action">Toggle Maximize</button><button id="setting-fullscreen" class="settings-action">Toggle Fullscreen</button><button id="setting-exit" class="settings-action">Exit Personal XMB</button>'],accounts:["Accounts",'<p class="xmb-settings-description">Enter provider settings, save them, then connect. Steam friend presence uses the Steam Web API.</p><div class="account-setup-grid"><label>Spotify Client ID<input id="account-spotify-client"></label><label>Steam Web API Key<input id="account-steam-key" type="password" autocomplete="new-password" placeholder="Saved securely — leave blank to keep existing key"></label><label>Steam ID<input id="account-steam-id" inputmode="numeric"></label><label>Discord Client ID<input id="account-discord-client"></label><label>Microsoft Client ID<input id="account-microsoft-client"></label><label>Riot Client ID<input id="account-riot-client"></label></div><button id="save-account-config" class="settings-action">Save Account Configuration</button><button id="connect-spotify" class="settings-action">Connect Spotify</button><button id="connect-discord" class="settings-action">Connect Discord</button><button id="connect-microsoft" class="settings-action">Connect Xbox / Microsoft</button><button id="connect-riot" class="settings-action">Connect Riot</button><div id="account-status" class="settings-status"></div>']}[section]||null;
 const x=d||{0:"General Settings",1:""};t.textContent=x[0];c.innerHTML=x[1];
 if(section==="themes"){const q=c.querySelector("#setting-theme");Object.keys(themes).forEach(n=>{const o=document.createElement("option");o.value=n;o.textContent=n.replace(/-/g," ");q.appendChild(o);});q.value=s.theme||"default";q.onchange=()=>{const n={...getUserSettings(),theme:q.value};saveUserSettings(n);applyUserSettings();};}
 if(section==="general")["clock","hints","animations"].forEach(k=>c.querySelector("#setting-"+k).onchange=e=>{const n={...getUserSettings(),[k]:e.target.checked};saveUserSettings(n);applyUserSettings();});
 if(section==="audio"){c.querySelector("#setting-sound").onchange=e=>{const n={...getUserSettings(),sound:e.target.checked};saveUserSettings(n);applyUserSettings();};c.querySelector("#setting-volume").oninput=e=>{const n={...getUserSettings(),soundVolume:+e.target.value};saveUserSettings(n);applyUserSettings();};}
 if(section==="artwork")c.querySelector("#setting-clear-cache").onclick=async()=>{const q=c.querySelector("#settings-cache-status"),r=await window.electron?.clearArtworkCache?.();q.textContent=r?.success?"Cache cleared. Relaunch to rebuild artwork.":"Unable to clear cache.";};
 if(section==="system"){c.querySelector("#setting-maximize").onclick=()=>window.electron?.setWindowState?.("maximize");c.querySelector("#setting-fullscreen").onclick=()=>window.electron?.setWindowState?.("fullscreen");c.querySelector("#setting-exit").onclick=()=>window.electron?.quitApp?.();}
 if(section==="accounts"){
  const cfg=window.xmbConfig||{};c.querySelector("#account-spotify-client").value=cfg.spotify?.clientId||"";c.querySelector("#account-steam-id").value=cfg.integrations?.steam?.steamId||"";if(cfg.integrations?.steam?.configured){c.querySelector("#account-steam-key").placeholder="Saved securely — leave blank to keep existing key";}c.querySelector("#account-discord-client").value=cfg.integrations?.discord?.clientId||"";c.querySelector("#account-microsoft-client").value=cfg.integrations?.microsoft?.clientId||"";c.querySelector("#account-riot-client").value=cfg.integrations?.riot?.clientId||"";
  c.querySelector("#save-account-config").onclick=async()=>{const v={spotifyClientId:c.querySelector("#account-spotify-client").value.trim(),steamApiKey:c.querySelector("#account-steam-key").value.trim(),steamId:c.querySelector("#account-steam-id").value.trim(),discordClientId:c.querySelector("#account-discord-client").value.trim(),microsoftClientId:c.querySelector("#account-microsoft-client").value.trim(),riotClientId:c.querySelector("#account-riot-client").value.trim()};const r=await window.electron?.saveSteamConfig?.({steamId:v.steamId,steamApiKey:v.steamApiKey});if(!r?.success){c.querySelector("#account-status").textContent=r?.error||"Unable to save Steam configuration.";return;}const accountResult=await window.electron?.saveAccountConfig?.(v);c.querySelector("#account-status").textContent=accountResult?.success?"Configuration saved. Steam API key is stored securely.":(accountResult?.error||"Unable to save configuration.");};
  [["spotify","connect-spotify"],["discord","connect-discord"],["microsoft","connect-microsoft"],["riot","connect-riot"]].forEach(([p,id])=>c.querySelector("#"+id).onclick=async()=>{const q=c.querySelector("#account-status");q.textContent="Connecting "+p+"...";const r=p==="spotify"?await window.electron?.spotifyLogin?.():await window.electron?.loginAccount?.(p);q.textContent=r?.success===false?(r.error||"Connection failed."):p+" authorization started in your browser.";});
 }
}
document.addEventListener("keydown",e=>{if(settingsBranch&&e.key==="Escape"){e.preventDefault();e.stopPropagation();closeSettingsPanel();}},true);
window.xmbSettings={open:openSettingsPanel,close:closeSettingsPanel,apply:applyUserSettings,openSection:renderSettingsSection};