const spotifyService={initialized:false,polling:false,pollTimer:null,currentTrack:null,shuffle:false,repeat:"off",async initialize(){if(this.initialized)return;this.initialized=true;await this.refreshNowPlaying();this.startPolling();},startPolling(){if(this.polling)return;this.polling=true;this.pollTimer=setInterval(()=>this.refreshNowPlaying(),5000);},stopPolling(){if(this.pollTimer)clearInterval(this.pollTimer);this.pollTimer=null;this.polling=false;},async api(r){const x=await window.electron?.spotifyApi?.(r);if(!x?.success)throw new Error(x?.error||"Spotify API request failed.");return x.data;},async refreshNowPlaying(){try{const r=await this.api({method:"GET",endpoint:"/me/player"});if(!r?.item){this.currentTrack=null;window.updateSpotifyPlayer?.(null);return;}const i=r.item;this.shuffle=!!r.shuffle_state;this.repeat=r.repeat_state||"off";this.currentTrack={id:i.id,name:i.name,artist:i.artists?.map(a=>a.name).join(", ")||"Unknown Artist",album:i.album?.name||"Unknown Album",artwork:i.album?.images?.[0]?.url||"",duration:i.duration_ms||0,progress:r.progress_ms||0,isPlaying:!!r.is_playing,spotifyUrl:i.external_urls?.spotify||""};window.updateSpotifyPlayer?.(this.currentTrack);this.updateModes();}catch(e){console.warn("Spotify refresh failed:",e.message);window.updateSpotifyPlayer?.(null);}},async login(){const r=await window.electron?.spotifyLogin?.();if(r?.success===false)throw new Error(r.error||"Spotify login failed.");},async togglePlayback(){if(!this.currentTrack)return;try{await this.api({method:"PUT",endpoint:this.currentTrack.isPlaying?"/me/player/pause":"/me/player/play"});setTimeout(()=>this.refreshNowPlaying(),350);}catch(e){console.warn("Spotify playback failed:",e.message);}},async next(){try{await this.api({method:"POST",endpoint:"/me/player/next"});setTimeout(()=>this.refreshNowPlaying(),500);}catch(e){console.warn(e.message);}},async previous(){try{await this.api({method:"POST",endpoint:"/me/player/previous"});setTimeout(()=>this.refreshNowPlaying(),500);}catch(e){console.warn(e.message);}},async toggleShuffle(){try{this.shuffle=!this.shuffle;await this.api({method:"PUT",endpoint:"/me/player/shuffle?state="+this.shuffle});this.updateModes();}catch(e){console.warn("Shuffle failed:",e.message);}},async cycleRepeat(){const m=["off","context","track"];this.repeat=m[(m.indexOf(this.repeat)+1)%m.length];try{await this.api({method:"PUT",endpoint:"/me/player/repeat?state="+this.repeat});this.updateModes();}catch(e){console.warn("Repeat failed:",e.message);}},updateModes(){document.getElementById("media-shuffle")?.classList.toggle("active",this.shuffle);document.getElementById("media-repeat")?.classList.toggle("active",this.repeat!=="off");},async recentlyPlayed(limit=20){return this.api({method:"GET",endpoint:"/me/player/recently-played?limit="+Math.min(50,limit)});},async playlists(limit=20){return this.api({method:"GET",endpoint:"/me/playlists?limit="+Math.min(50,limit)});}};
document.addEventListener("DOMContentLoaded",()=>{document.getElementById("media-play")?.addEventListener("click",()=>spotifyService.togglePlayback());document.getElementById("media-next")?.addEventListener("click",()=>spotifyService.next());document.getElementById("media-previous")?.addEventListener("click",()=>spotifyService.previous());document.getElementById("media-shuffle")?.addEventListener("click",()=>spotifyService.toggleShuffle());document.getElementById("media-repeat")?.addEventListener("click",()=>spotifyService.cycleRepeat());window.electron?.onSpotifyAuthComplete?.(()=>spotifyService.refreshNowPlaying());});window.spotifyService=spotifyService;
const spotifyUi={
    ensure(){
        let o=document.getElementById("spotify-library-overlay");
        if(o)return o;
        o=document.createElement("div");o.id="spotify-library-overlay";
        o.innerHTML='<div class="spotify-library-panel"><div class="spotify-library-header"><div><div class="spotify-library-kicker">SPOTIFY</div><h2 id="spotify-library-title"></h2></div><button id="spotify-library-close">ESC</button></div><div id="spotify-library-content"></div></div>';
        document.body.appendChild(o);o.querySelector("#spotify-library-close").onclick=()=>o.classList.remove("visible");return o;
    },
    async showRecentlyPlayed(){
        const o=this.ensure(),c=o.querySelector("#spotify-library-content");o.querySelector("#spotify-library-title").textContent="Recently Played";o.classList.add("visible");c.textContent="Loading...";
        try{const d=await spotifyService.recentlyPlayed(20);c.innerHTML=(d?.items||[]).map(x=>'<div class="spotify-library-row"><img src="'+(x.track?.album?.images?.[2]?.url||"")+'"><div><strong></strong><span></span></div></div>').join("")||"<p>No recently played tracks.</p>";(d?.items||[]).forEach((x,i)=>{const rows=c.querySelectorAll(".spotify-library-row")[i];rows.querySelector("strong").textContent=x.track?.name||"Unknown";rows.querySelector("span").textContent=x.track?.artists?.map(a=>a.name).join(", ")||"";});}catch(e){c.textContent=e.message;}
    },
    async showPlaylists(){
        const o=this.ensure(),c=o.querySelector("#spotify-library-content");o.querySelector("#spotify-library-title").textContent="Playlists";o.classList.add("visible");c.textContent="Loading...";
        try{const d=await spotifyService.playlists(20);c.innerHTML=(d?.items||[]).map(x=>'<button class="spotify-playlist-row" data-uri="'+x.uri+'"><img src="'+(x.images?.[2]?.url||x.images?.[0]?.url||"")+'"><span></span></button>').join("")||"<p>No playlists found.</p>";(d?.items||[]).forEach((x,i)=>c.querySelectorAll(".spotify-playlist-row")[i].querySelector("span").textContent=x.name);c.querySelectorAll(".spotify-playlist-row").forEach(b=>b.onclick=()=>spotifyService.api({method:"PUT",endpoint:"/me/player/play",body:{context_uri:b.dataset.uri}}).then(()=>spotifyService.refreshNowPlaying()));}catch(e){c.textContent=e.message;}
    }
};
window.spotifyUi=spotifyUi;
