const spotifyService={
    initialized:false,polling:false,pollTimer:null,currentTrack:null,shuffle:false,repeat:"off",
    async initialize(){if(this.initialized)return;this.initialized=true;await this.refreshNowPlaying();this.startPolling();},
    startPolling(){if(this.polling)return;this.polling=true;this.pollTimer=setInterval(()=>this.refreshNowPlaying(),5000);},
    stopPolling(){if(this.pollTimer)clearInterval(this.pollTimer);this.pollTimer=null;this.polling=false;},
    async api(request){const r=await window.electron?.spotifyApi?.(request);if(!r?.success)throw new Error(r?.error||"Spotify API request failed.");return r.data;},
    async refreshNowPlaying(){try{const response=await this.api({method:"GET",endpoint:"/me/player"});if(!response?.item){this.currentTrack=null;this.updateInterface(null);return;}const item=response.item;this.shuffle=!!response.shuffle_state;this.repeat=response.repeat_state||"off";this.currentTrack={id:item.id,name:item.name,artist:item.artists?.map(a=>a.name).join(", ")||"Unknown Artist",album:item.album?.name||"Unknown Album",artwork:item.album?.images?.[0]?.url||"",duration:item.duration_ms||0,progress:response.progress_ms||0,isPlaying:!!response.is_playing,spotifyUrl:item.external_urls?.spotify||""};this.updateInterface(this.currentTrack);}catch(e){console.warn("Spotify refresh failed:",e.message);this.updateInterface(null);}},
    updateInterface(track){window.updateSpotifyPlayer?.(track);},
    async login(){const r=await window.electron?.spotifyLogin?.();if(r?.success===false)throw new Error(r.error||"Spotify login failed.");},
    async togglePlayback(){if(!this.currentTrack)return;try{await this.api({method:"PUT",endpoint:this.currentTrack.isPlaying?"/me/player/pause":"/me/player/play"});setTimeout(()=>this.refreshNowPlaying(),350);}catch(e){console.warn("Spotify playback toggle failed:",e.message);}},
    async next(){try{await this.api({method:"POST",endpoint:"/me/player/next"});setTimeout(()=>this.refreshNowPlaying(),500);}catch(e){console.warn("Spotify next failed:",e.message);}},
    async previous(){try{await this.api({method:"POST",endpoint:"/me/player/previous"});setTimeout(()=>this.refreshNowPlaying(),500);}catch(e){console.warn("Spotify previous failed:",e.message);}},
    async toggleShuffle(){try{this.shuffle=!this.shuffle;await this.api({method:"PUT",endpoint:`/me/player/shuffle?state=${this.shuffle}`});this.updateModes();}catch(e){console.warn("Spotify shuffle failed:",e.message);}},
    async cycleRepeat(){const modes=["off","context","track"];this.repeat=modes[(modes.indexOf(this.repeat)+1)%modes.length];try{await this.api({method:"PUT",endpoint:`/me/player/repeat?state=${this.repeat}`});this.updateModes();}catch(e){console.warn("Spotify repeat failed:",e.message);}},
    updateModes(){document.getElementById("media-shuffle")?.classList.toggle("active",this.shuffle);document.getElementById("media-repeat")?.classList.toggle("active",this.repeat!=="off");},
    async recentlyPlayed(limit=20){return this.api({method:"GET",endpoint:`/me/player/recently-played?limit=${Math.min(50,Math.max(1,limit))}`});},
    async playlists(limit=20){return this.api({method:"GET",endpoint:`/me/playlists?limit=${Math.min(50,Math.max(1,limit))}`});}
};
document.addEventListener("DOMContentLoaded",()=>{document.getElementById("media-play")?.addEventListener("click",()=>spotifyService.togglePlayback());document.getElementById("media-next")?.addEventListener("click",()=>spotifyService.next());document.getElementById("media-previous")?.addEventListener("click",()=>spotifyService.previous());document.getElementById("media-shuffle")?.addEventListener("click",()=>spotifyService.toggleShuffle());document.getElementById("media-repeat")?.addEventListener("click",()=>spotifyService.cycleRepeat());window.electron?.onSpotifyAuthComplete?.(()=>spotifyService.refreshNowPlaying());});
window.spotifyService=spotifyService;